### ISSUE TITLE
Tests: list index out of range error

### ISSUE THREAD

**Issue by theoturner** [manuelzander/iota_simulation#3]
I get the same index out of range error in 5 tests, all on `self.no_of_transactions = self.config[0][0]`.

Error:
```
'PARAMETERS'
E'PARAMETERS'
E'PARAMETERS'
E'PARAMETERS'
E'PARAMETERS'
E
======================================================================
ERROR: test_calculation_conf_conf (tests.test_basic.AfterSimulationWeightedRandomWalkTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/theo/iota_simulation/tests/test_basic.py", line 35, in setUp
    self.simu = Multi_Agent_Simulation(100, 10, 2, 0.005, 1, distances, "weighted")
  File "/Users/theo/iota_simulation/simulation/simulation_multi_agent.py", line 27, in __init__
    self.no_of_transactions = self.config[0][0]
IndexError: list index out of range

======================================================================
ERROR: test_calculation_cum_weight (tests.test_basic.AfterSimulationWeightedRandomWalkTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/theo/iota_simulation/tests/test_basic.py", line 35, in setUp
    self.simu = Multi_Agent_Simulation(100, 10, 2, 0.005, 1, distances, "weighted")
  File "/Users/theo/iota_simulation/simulation/simulation_multi_agent.py", line 27, in __init__
    self.no_of_transactions = self.config[0][0]
IndexError: list index out of range

======================================================================
ERROR: test_calculation_exit_probabilities (tests.test_basic.AfterSimulationWeightedRandomWalkTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/theo/iota_simulation/tests/test_basic.py", line 35, in setUp
    self.simu = Multi_Agent_Simulation(100, 10, 2, 0.005, 1, distances, "weighted")
  File "/Users/theo/iota_simulation/simulation/simulation_multi_agent.py", line 27, in __init__
    self.no_of_transactions = self.config[0][0]
IndexError: list index out of range

======================================================================
ERROR: test_simulation_run (tests.test_basic.SimulationSetupAndRunTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/theo/iota_simulation/tests/test_basic.py", line 17, in setUp
    self.simu = Multi_Agent_Simulation(100, 10, 2, 0.005, 1, distances, "weighted")
  File "/Users/theo/iota_simulation/simulation/simulation_multi_agent.py", line 27, in __init__
    self.no_of_transactions = self.config[0][0]
IndexError: list index out of range

======================================================================
ERROR: test_simulation_setup (tests.test_basic.SimulationSetupAndRunTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/theo/iota_simulation/tests/test_basic.py", line 17, in setUp
    self.simu = Multi_Agent_Simulation(100, 10, 2, 0.005, 1, distances, "weighted")
  File "/Users/theo/iota_simulation/simulation/simulation_multi_agent.py", line 27, in __init__
    self.no_of_transactions = self.config[0][0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)

```

**Comment by manuelzander** [comment]
Fixed by using `pytest`. What really needs to happen though (if I will ever have the time for it 😌), is to re-think how `Multi_Agent_Simulation` is initialized, and how configuration can be improved.

**Comment by manuelzander** [comment]
Fixed by using `pytest`. What really needs to happen though (if I will ever have the time for it 😌), is to re-think how `Multi_Agent_Simulation` is initialized, and how configuration can be improved.
